const para=[`Apple Inc. is an American multinational technology company headquartered in Cupertino, California, that designs, develops, and sells consumer electronics, computer software, and online services. It is considered one of the Big Tech technology companies, alongside Amazon, Google, Microsoft, and Facebook.[8][9][10]`,
`The company's hardware products include the iPhone smartphone, the iPad tablet computer, the Mac personal computer, the iPod portable media player, the Apple Watch smartwatch, the Apple TV digital media player, the AirPods wireless earbuds and the HomePod smart speaker. Apple's software includes macOS, iOS, iPadOS, watchOS, and tvOS operating systems, the iTunes media player, the Safari web browser, the Shazam music identifier, and the iLife and iWork creativity and productivity suites, as well as professional applications like Final Cut Pro, Logic Pro, and Xcode. Its online services include the iTunes Store, the iOS App Store, Mac App Store, Apple Music, Apple TV+, iMessage, and iCloud. Other services include Apple Store, Genius Bar, AppleCare, Apple Pay, Apple Pay Cash, and Apple Card.`,
`Apple was founded by Steve Jobs, Steve Wozniak, and Ronald Wayne in April 1976 to develop and sell Wozniak's Apple I personal computer, though Wayne sold his share back within 12 days. It was incorporated as Apple Computer, Inc., in January 1977, and sales of its computers, including the Apple II, grew quickly. Within a few years, Jobs and Wozniak had hired a staff of computer designers and had a production line. Apple went public in 1980 to instant financial success. Over the next few years, Apple shipped new computers featuring innovative graphical user interfaces, such as the original Macintosh in 1984, and Apple's marketing advertisements for its products received widespread critical acclaim. However, the high price of its products and limited application library caused problems, as did power struggles between executives. In 1985, Wozniak departed Apple amicably and remained an honorary employee,[11] while Jobs and others resigned to found NeXT.[12]`,
`As the market for personal computers expanded and evolved through the 1990s, Apple lost market share to the lower-priced duopoly of Microsoft Windows on Intel PC clones. The board recruited CEO Gil Amelio to what would be a 500-day charge for him to rehabilitate the financially troubled company—reshaping it with layoffs, executive restructuring, and product focus. In 1997, he led Apple to buy NeXT, solving the desperately failed operating system strategy and bringing Jobs back. Jobs pensively regained leadership status, becoming CEO in 2000. Apple swiftly returned to profitability under the revitalizing Think different campaign, as he rebuilt Apple's status by launching the iMac in 1998, opening the retail chain of Apple Stores in 2001, and acquiring numerous companies to broaden the software portfolio. In January 2007, Jobs renamed the company Apple Inc., reflecting its shifted focus toward consumer electronics, and launched the iPhone to great critical acclaim and financial success. In August 2011, Jobs resigned as CEO due to health complications, and Tim Cook became the new CEO. Two months later, Jobs died, marking the end of an era for the company. In June 2019, Jony Ive, Apple's CDO, left the company to start his own firm, but stated he would work with Apple as its primary client.`,
`Apple is well known for its size and revenues. Its worldwide annual revenue totaled $265 billion for the 2018 fiscal year. Apple is the world's largest technology company by revenue and one of the world's most valuable companies. It is also the world's third-largest mobile phone manufacturer after Samsung and Huawei.[13] In August 2018, Apple became the first publicly traded U.S. company to be valued at over $1 trillion[14][15] and just two years later in August 2020 became the first $2 trillion U.S. company.[16][17] The company employs 137,000 full-time employees[18] and maintains 510 retail stores in 25 countries as of 2020.[19] It operates the iTunes Store, which is the world's largest music retailer. As of January 2020, more than 1.5 billion Apple products are actively in use worldwide.[20] The company also has a high level of brand loyalty and is ranked as the world's most valuable brand. However, Apple receives significant criticism regarding the labor practices of its contractors, its environmental practices and unethical business practices, including anti-competitive behavior, as well as the origins of source materials`,
`Samsung was founded by Lee Byung-chul in 1938 as a trading company. Over the next three decades, the group diversified into areas including food processing, textiles, insurance, securities, and retail. Samsung entered the electronics industry in the late 1960s and the construction and shipbuilding industries in the mid-1970s; these areas would drive its subsequent growth. Following Lee's death in 1987, Samsung was separated into four business groups – Samsung Group, Shinsegae Group, CJ Group and Hansol Group. Since 1990, Samsung has increasingly globalised its activities and electronics; in particular, its mobile phones and semiconductors have become its most important source of income. As of 2017, Samsung has the 6th highest global brand value.[6]`,
`Notable Samsung industrial affiliates include Samsung Electronics (the world's largest information technology company, consumer electronics maker and chipmaker measured by 2017 revenues),[7][8] Samsung Heavy Industries (the world's 2nd largest shipbuilder measured by 2010 revenues),[9] and Samsung Engineering and Samsung C&T (respectively the world's 13th and 36th largest construction companies).[10] Other notable subsidiaries include Samsung Life Insurance (the world's 14th largest life insurance company),[11] Samsung Everland (operator of Everland Resort, the oldest theme park in South Korea)[12] and Cheil Worldwide (the world's 15th largest advertising agency, as measured by 2012 revenues)`,
`Sony is one the biggest producers of image sensors, with a 50% market share as of 2019.[11] Many digital camera brands and smartphone makers implement Sony IMX image sensors, with some brands such as Apple, Nikon, Samsung, LG, Huawei, and Olympus.[12]`,
`Sony Corporation (ソニー株式会社, Sonī Kabushiki Kaisha, /ˈsoʊni/ SOH-nee, commonly known as Sony and stylized as SONY) is a Japanese multinational conglomerate corporation headquartered in Kōnan, Minato, Tokyo.[7][1] The company owns the largest music entertainment business in the world,[8] the largest video game console business and the second largest video game publishing business, and is one of the leading manufacturers of electronic products for the consumer and professional markets, and a leading player in the film and television entertainment industry.[9] Sony was ranked 97th on the 2018 Fortune Global 500 list.[10`,
`BlackBerry is a line of smartphones, tablets, and services originally designed and marketed by Canadian company BlackBerry Limited (formerly known as Research In Motion, or RIM).[1] BlackBerry products were formally designed, manufactured, and marketed by Chinese company TCL Communication (under the brand of BlackBerry Mobile), Indonesian company BB Merah Putih, and Indian company Optiemus Infracom for the global, Indonesian, and South Asian markets (respectively) using the BlackBerry brand under license. TCL stopped manufacturing the devices on August 31, 2020, as its contract expired, with the last Blackberry-TCL phone being the Blackberry Key2LE.[2][3]`,
`The BlackBerry line traditionally uses a proprietary operating system developed by BlackBerry Limited known as BlackBerry OS. In 2013, BlackBerry introduced BlackBerry 10, a major revamp of the platform based on the QNX operating system. BlackBerry 10 was meant to replace the aging BlackBerry OS platform with a new system that was more in line with the user experiences of modern smartphone operating systems. The first BB10 powered device was the BlackBerry Z10, which was followed by other all-touch and keyboard-equipped models; including the BlackBerry Q10, BlackBerry Classic, Blackberry`,
];
const paraContainer=document.querySelector(".para");
const amount=document.querySelector("#amount");
const form=document.querySelector(".lorem-form");
const btn=document.querySelector(".btn");
btn.addEventListener("click",()=>{
    const value=parseInt(amount.value);
    const random=Math.floor(Math.random()*para.length);
    if(isNaN(value) || value<0 || value>para.length)
    {
        paraContainer.innerHTML=`<p>${para[random]}</p>`;
    }
    else
    {
        const selectpara=para.slice(0,value);
        const show=selectpara.map(item=>{
            return `<p>${item}</P>`
        }).join(``);
      paraContainer.innerHTML=show;
    }
   
});